In [1]:
import tensorflow as tf 
from tensorflow import keras as keras
from tensorflow.python.keras import backend as K
import os
import numpy as np
import datetime
import importlib


import Clone_Model
import rsc

In [2]:
checkpoint_path = "./cloning/checkpoints/cloning/default_checkpoint.ckpt"
checkpoint_dir = os.path.dirname(checkpoint_path)
ckpt_callback = tf.keras.callbacks.ModelCheckpoint(filepath=checkpoint_path, save_weights_only=True, verbose=1)

log_dir_clone = "./cloning/logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir=log_dir_clone, histogram_freq=1)

In [43]:
#      CLONE MODEL EAGER ENABLED
###########################################

importlib.reload(rsc)
importlib.reload(Clone_Model)

if not tf.executing_eagerly(): tf.compat.v1.enable_eager_execution()

K.clear_session()

batch_size = 3

train, test = rsc.get_titanic_dataset()


model = rsc.get_model(None)

model.compile(
    optimizer=keras.optimizers.Adam(),
    loss=keras.losses.BinaryCrossentropy(),
    run_eagerly = tf.executing_eagerly()
    )


history = model.fit(train,
                    batch_size=batch_size,
                    epochs=1, 
                    steps_per_epoch=3, 
                    validation_data=test, 
                    validation_steps=1, 
                    callbacks=[tensorboard_callback])


clone = Clone_Model.satify_model(model)

clone.compile(optimizer=keras.optimizers.Adam(),
              loss=keras.losses.BinaryCrossentropy(),
              run_eagerly = tf.executing_eagerly())

history = clone.fit(train,
                    batch_size=batch_size,
                    epochs = 1,
                    steps_per_epoch=3,
                    validation_data=test, 
                    validation_steps=1, 
                    callbacks=[tensorboard_callback])
                

3/3 [==============================] - 0s 14ms/step - loss: 2.1462 - val_loss: 1.5166
input tensor has shape: (None, 21)
input tensor has shape: (None, 22)
input tensor has shape: (None, 23)
input tensor has shape: (None, 24)
input tensor has shape: (None, 2)
input tensor has shape: (None, 21)
input tensor has shape: (None, 22)
input tensor has shape: (None, 23)
input tensor has shape: (None, 24)
input tensor has shape: (None, 2)
input tensor has shape: (20, 21)
input tensor has shape: (20, 22)
input tensor has shape: (20, 23)
input tensor has shape: (20, 24)
input tensor has shape: (20, 2)
1/3 [=========>....................] - ETA: 0s - loss: 1.6998 - observed_samples_sat_dense_1: 18.5163 - observed_samples_sat_dense_2: 20.0768 - observed_samples_sat_dense_3: 18.5418 - observed_samples_sat_dense_4: 18.8909 - observed_samples_sat_predictions: 21.0235input tensor has shape: (20, 21)
input tensor has shape: (20, 22)
input tensor has shape: (20, 23)
input tensor has shape: (20, 24)
input

In [46]:
#(None, 21, 5)[1:]*2
#np.zeros(shape=(None))
importlib.reload(rsc)
train_b, test_b = rsc.get_titanic_dataset(batch_size=3)
print(train_b)
print(model(np.array([[1,2,3,4] ])))

for ix, x in enumerate(train_b):
    print(x)

<BatchDataset shapes: ((None, None, 4), (None, None, 2)), types: (tf.float32, tf.int32)>
tf.Tensor([[0.69211704 0.3078829 ]], shape=(1, 2), dtype=float32)
(<tf.Tensor: shape=(3, 20, 4), dtype=float32, numpy=
array([[[ 61.    ,   0.    ,   0.    ,  32.3208],
        [ 38.    ,   0.    ,   1.    , 153.4625],
        [ 36.    ,   0.    ,   0.    ,  26.3875],
        [ 28.    ,   0.    ,   0.    ,  26.55  ],
        [ 22.    ,   0.    ,   0.    ,  10.5167],
        [ 28.    ,   3.    ,   1.    ,  25.4667],
        [ 28.    ,   0.    ,   0.    ,   7.8958],
        [ 30.    ,   0.    ,   0.    ,   7.8958],
        [ 34.    ,   1.    ,   0.    ,  21.    ],
        [  3.    ,   4.    ,   2.    ,  31.3875],
        [ 31.    ,   1.    ,   0.    ,  57.    ],
        [ 16.    ,   0.    ,   0.    ,   8.05  ],
        [ 28.    ,   3.    ,   1.    ,  25.4667],
        [ 39.    ,   0.    ,   0.    ,   0.    ],
        [ 28.    ,   0.    ,   0.    , 227.525 ],
        [ 19.    ,   0.    ,   0.    ,   7

InvalidArgumentError: Cannot add tensor to the batch: number of elements does not match. Shapes are: [tensor]: [7,4], [batch]: [20,4]