In [1]:
import tensorflow as tf 
from tensorflow import keras as keras
from tensorflow.python.keras import backend as K
import os
import numpy as np
import datetime
import importlib


import Clone_Model
import rsc

In [2]:
checkpoint_path = "./cloning/checkpoints/cloning/default_checkpoint.ckpt"
checkpoint_dir = os.path.dirname(checkpoint_path)
ckpt_callback = tf.keras.callbacks.ModelCheckpoint(filepath=checkpoint_path, save_weights_only=True, verbose=1)

log_dir_clone = "./cloning/logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir=log_dir_clone, histogram_freq=1)

In [39]:
#      CLONE MODEL EAGER ENABLED
###########################################

importlib.reload(rsc)
importlib.reload(Clone_Model)

if not tf.executing_eagerly(): tf.compat.v1.enable_eager_execution()

K.clear_session()

batch_size = 3

train, test = rsc.get_titanic_dataset()


model = rsc.get_model_slim()

model.compile(
    optimizer=keras.optimizers.Adam(),
    loss=keras.losses.BinaryCrossentropy(),
    run_eagerly = tf.executing_eagerly()
    )


history = model.fit(train,
                    batch_size=batch_size,
                    epochs=1, 
                    steps_per_epoch=3, 
                    validation_data=test, 
                    validation_steps=1, 
                    callbacks=[tensorboard_callback])


clone = Clone_Model.satify_model(model)

clone.compile(optimizer=keras.optimizers.Adam(),
              loss=keras.losses.BinaryCrossentropy(),
              run_eagerly = tf.executing_eagerly())

sat_cb = Clone_Model.sat_results()

history = clone.fit(train,
                    batch_size=batch_size,
                    epochs = 1,
                    steps_per_epoch=3,
                    validation_data=test, 
                    validation_steps=1, 
                    callbacks=[tensorboard_callback, sat_cb])
                

3/3 [==============================] - 0s 12ms/step - loss: 0.6941 - val_loss: 0.6961
Init Satlayer!
Init Satlayer!
Init Satlayer!
Init Satlayer!
Init Satlayer!
SatLayer.update(): Input tensor has shape: (None, 3)
SatLayer.update(): Input tensor has shape: (None, 3)
SatLayer.update(): Input tensor has shape: (None, 2)
SatLayer.update(): Input tensor has shape: (None, 2)
SatLayer.update(): Input tensor has shape: (None, 2)
SatLayer.update(): Input tensor has shape: (None, 3)
SatLayer.update(): Input tensor has shape: (None, 3)
SatLayer.update(): Input tensor has shape: (None, 2)
SatLayer.update(): Input tensor has shape: (None, 2)
SatLayer.update(): Input tensor has shape: (None, 2)
Clone_Model.satify_model() end.
SatLayer.update(): Input tensor has shape: (20, 3)
SatLayer.update(): Input tensor has shape: (20, 3)
SatLayer.update(): Input tensor has shape: (20, 2)
SatLayer.update(): Input tensor has shape: (20, 2)
SatLayer.update(): Input tensor has shape: (20, 2)
1/3 [=========>.......

In [114]:
#      TRAIN MODEL EAGER ENABLED MNIST CLASSIFICATION
###########################################

importlib.reload(rsc)
importlib.reload(Clone_Model)

if not tf.executing_eagerly(): tf.compat.v1.enable_eager_execution()

K.clear_session()

batch_size = 20

train, test = rsc.get_mnist()


model = rsc.get_model_unitlist(hidden_layers_spec=[128])

model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])



history = model.fit(train[0],
                    train[1],
                    batch_size=batch_size,
                    epochs=10, 
                    steps_per_epoch=None, 
                    validation_data=test, 
                    validation_steps=1, 
                    callbacks=[tensorboard_callback])



Epoch 1/10
3000/3000 [==============================] - 12s 4ms/step - loss: 2.2026 - accuracy: 0.8638 - val_loss: 0.7533 - val_accuracy: 0.9000
Epoch 2/10
3000/3000 [==============================] - 10s 3ms/step - loss: 0.3796 - accuracy: 0.9107 - val_loss: 0.2871 - val_accuracy: 0.9000
Epoch 3/10
3000/3000 [==============================] - 9s 3ms/step - loss: 0.2980 - accuracy: 0.9265 - val_loss: 0.2013 - val_accuracy: 0.9000
Epoch 4/10
3000/3000 [==============================] - 9s 3ms/step - loss: 0.2702 - accuracy: 0.9352 - val_loss: 0.2948 - val_accuracy: 0.9500
Epoch 5/10
3000/3000 [==============================] - 8s 3ms/step - loss: 0.2509 - accuracy: 0.9410 - val_loss: 0.3036 - val_accuracy: 0.9000
Epoch 6/10
3000/3000 [==============================] - 7s 2ms/step - loss: 0.2457 - accuracy: 0.9428 - val_loss: 0.1963 - val_accuracy: 0.9000
Epoch 7/10
3000/3000 [==============================] - 10s 3ms/step - loss: 0.2393 - accuracy: 0.9457 - val_loss: 0.2068 - val_accura

In [148]:
#      CLONE MODEL EAGER ENABLED MNIST CLASSIFICATION
###########################################

importlib.reload(rsc)
importlib.reload(Clone_Model)


clone = Clone_Model.satify_model(model)

"""clone.compile(optimizer=keras.optimizers.Adam(),
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              run_eagerly = tf.executing_eagerly())
"""
sat_cb = Clone_Model.sat_results()

history = clone.fit(train[0],
                    train[1],
                    batch_size=40,
                    epochs = 1,
                    steps_per_epoch=1,
                    validation_data=test, 
                    validation_steps=1, 
                    callbacks=[tensorboard_callback, sat_cb])
              

<class 'tensorflow.python.keras.layers.core.Flatten'>
RESET Weights!
RESET Weights!
Clone_Model.satify_model() end.
1/1 [==============================] - ETA: 0s - loss: 4.9593 - accuracy: 0.9574 - observed_samples_sat_dense: 39.0237 - observed_samples_sat_dense_1: 40.3908
Trace of covmat: -230258072.7582154
Sum Evals raw: (-230258072.7582156+3.242207319277864e-16j)
Sum Evals abs: -230258072.7582156
abs(rsum(comp_evals)): 230258072.7582156
Comp Evals dtype: <dtype: 'complex128'>
Evals: [ 4.67635675e-04+5.57981429e-20j -9.68884097e-04+2.25273535e-20j
 -1.76426689e-03-5.89952610e-21j  1.88072415e-03-3.14275913e-19j
 -1.75547689e-03+1.60565754e-03j -1.75547689e-03-1.60565754e-03j
  2.67318798e-03-2.18890978e-03j  2.67318798e-03+2.18890978e-03j
  3.59832182e-03-1.04612125e-03j  3.59832182e-03+1.04612125e-03j
 -1.61699329e-03+3.38407708e-03j -1.61699329e-03-3.38407708e-03j
 -2.47217415e-03-2.92063998e-03j -2.47217415e-03+2.92063998e-03j
 -3.84178463e-03-1.42018100e-03j -3.84178463e-03+1.42

NameError: name 'k_s_ixs' is not defined

In [62]:
in_shape = model.layers[0].input_shape[-2:]
print(in_shape)
np.ones(shape=in_shape).shape

(28, 28)


(28, 28)

In [46]:
#(None, 21, 5)[1:]*2
#np.zeros(shape=(None))
importlib.reload(rsc)
train_b, test_b = rsc.get_titanic_dataset(batch_size=3)
print(train_b)
print(model(np.array([[1,2,3,4] ])))

for ix, x in enumerate(train_b):
    print(x)

<BatchDataset shapes: ((None, None, 4), (None, None, 2)), types: (tf.float32, tf.int32)>
tf.Tensor([[0.69211704 0.3078829 ]], shape=(1, 2), dtype=float32)
(<tf.Tensor: shape=(3, 20, 4), dtype=float32, numpy=
array([[[ 61.    ,   0.    ,   0.    ,  32.3208],
        [ 38.    ,   0.    ,   1.    , 153.4625],
        [ 36.    ,   0.    ,   0.    ,  26.3875],
        [ 28.    ,   0.    ,   0.    ,  26.55  ],
        [ 22.    ,   0.    ,   0.    ,  10.5167],
        [ 28.    ,   3.    ,   1.    ,  25.4667],
        [ 28.    ,   0.    ,   0.    ,   7.8958],
        [ 30.    ,   0.    ,   0.    ,   7.8958],
        [ 34.    ,   1.    ,   0.    ,  21.    ],
        [  3.    ,   4.    ,   2.    ,  31.3875],
        [ 31.    ,   1.    ,   0.    ,  57.    ],
        [ 16.    ,   0.    ,   0.    ,   8.05  ],
        [ 28.    ,   3.    ,   1.    ,  25.4667],
        [ 39.    ,   0.    ,   0.    ,   0.    ],
        [ 28.    ,   0.    ,   0.    , 227.525 ],
        [ 19.    ,   0.    ,   0.    ,   7

InvalidArgumentError: Cannot add tensor to the batch: number of elements does not match. Shapes are: [tensor]: [7,4], [batch]: [20,4]